redmine-6.0.4/config/routes.rb
        get 'rename'
        post 'rename'
        get 'history'
        get 'diff'
        match 'preview', :via => [:post, :put, :patch]
        post 'protect'
        post 'add_attachment'
      end
      collection do
        get 'export'
        get 'date_index'
        post 'new'
      end
    end
    match 'wiki', :controller => 'wiki', :action => 'show', :via => :get
    get 'wiki/:id/:version', :to => 'wiki#show', :constraints => {:version => /\d+/}
    delete 'wiki/:id/:version', :to => 'wiki#destroy_version'
    get 'wiki/:id/:version/annotate', :to => 'wiki#annotate'
    get 'wiki/:id/:version/diff', :to => 'wiki#diff'
  end

  resources :issues do
    member do
      # Used when updating the form of an existing issue
      patch 'edit', :to => 'issues#edit'
      get 'tab/:name', :action => 'issue_tab', :as => 'tab'
    end
    collection do
      match 'bulk_edit', :via => [:get, :post]
      match 'bulk_update', :via => [:post, :patch]
    end
    resources :time_entries, :controller => 'timelog', :only => [:new, :create]
    shallow do
      resources :relations, :controller => 'issue_relations', :only => [:index, :show, :create, :destroy]
    end
  end
  # Used when updating the form of a new issue outside a project
  post '/issues/new', :to => 'issues#new'
  match '/issues', :controller => 'issues', :action => 'destroy', :via => :delete

  resources :queries, :except => [:show]
  get '/queries/filter', :to => 'queries#filter', :as => 'queries_filter'

  resources :news, :only => [:index, :show, :edit, :update, :destroy, :create, :new]
  match '/news/:id/comments', :to => 'comments#create', :via => :post
  match '/news/:id/comments/:comment_id', :to => 'comments#destroy', :via => :delete

  resources :versions, :only => [:show, :edit, :update, :destroy] do
    post 'status_by', :on => :member
  end

  resources :documents, :only => [:show, :edit, :update, :destroy] do
    post 'add_attachment', :on => :member
  end

  match '/time_entries/context_menu', :to => 'context_menus#time_entries', :as => :time_entries_context_menu, :via => [:get, :post]

  resources :time_entries, :controller => 'timelog', :except => :destroy do
    member do
      # Used when updating the edit form of an existing time entry
      patch 'edit', :to => 'timelog#edit'
    end
    collection do
      get 'report'
      get 'bulk_edit'
      post 'bulk_update'
    end
  end
  match '/time_entries/:id', :to => 'timelog#destroy', :via => :delete, :id => /\d+/
  # TODO: delete /time_entries for bulk deletion
  match '/time_entries/destroy', :to => 'timelog#destroy', :via => :delete
  # Used to update the new time entry form
  post '/time_entries/new', :to => 'timelog#new'
  # Used to update the bulk edit time entry form
  post '/time_entries/bulk_edit', :to => 'timelog#bulk_edit'

  get 'projects/:id/activity', :to => 'activities#index', :as => :project_activity
  get 'activity', :to => 'activities#index'

  # repositories routes
  get 'projects/:id/repository/:repository_id/statistics', :to => 'repositories#stats'
  get 'projects/:id/repository/:repository_id/graph', :to => 'repositories#graph'
  post 'projects/:id/repository/:repository_id/fetch_changesets', :to => 'repositories#fetch_changesets'

  get 'projects/:id/repository/:repository_id/revisions/:rev', :to => 'repositories#revision'
  get 'projects/:id/repository/:repository_id/revision', :to => 'repositories#revision'
  post   'projects/:id/repository/:repository_id/revisions/:rev/issues', :to => 'repositories#add_related_issue'
  delete 'projects/:id/repository/:repository_id/revisions/:rev/issues/:issue_id', :to => 'repositories#remove_related_issue'
  get 'projects/:id/repository/:repository_id/revisions', :to => 'repositories#revisions'
  %w(browse show entry raw annotate).each do |action|
    get "projects/:id/repository/:repository_id/revisions/:rev/#{action}(/*path)",
        :controller => 'repositories',
        :action => action,
        :format => 'html',
        :constraints => {:rev => /[a-z0-9\.\-_]+/, :path => /.*/}
  end

  %w(browse entry raw changes annotate).each do |action|
    get "projects/:id/repository/:repository_id/#{action}(/*path)",
        :controller => 'repositories',
        :action => action,
        :format => 'html',
        :constraints => {:path => /.*/}
  end

  get "projects/:id/repository/:repository_id/revisions/:rev/diff(/*path)",
      :to => 'repositories#diff',
      :format => 'html',
      :constraints => {:rev => /[a-z0-9\.\-_]+/, :path => /.*/, :format => /(html|diff)/ }

  get "projects/:id/repository/:repository_id/diff(/*path)",
      :to => 'repositories#diff',
      :format => 'html',
      :constraints => {:path => /.*/, :format => /(html|diff)/ }

  get 'projects/:id/repository/:repository_id/show/*path', :to => 'repositories#show', :format => 'html', :constraints => {:path => /.*/}

  get 'projects/:id/repository/:repository_id', :to => 'repositories#show', :path => nil
  get 'projects/:id/repository', :to => 'repositories#show', :path => nil

  # additional routes for having the file name at the end of url
  get 'attachments/:id/:filename', :to => 'attachments#show', :id => /\d+/, :filename => /.*/, :as => 'named_attachment', :format => 'html'
  get 'attachments/download/:id/:filename', :to => 'attachments#download', :id => /\d+/, :filename => /.*/, :as => 'download_named_attachment'
  get 'attachments/download/:id', :to => 'attachments#download', :id => /\d+/
  get 'attachments/thumbnail/:id(/:size)', :to => 'attachments#thumbnail', :id => /\d+/, :size => /\d+/, :as => 'thumbnail'
  resources :attachments, :only => [:show, :update, :destroy]

  # register plugin object types with ObjectTypeConstraint.register_object_type(PluginModel.name.underscore.pluralize')
  constraints Redmine::Acts::Attachable::ObjectTypeConstraint do
    get 'attachments/:object_type/:object_id/edit', :to => 'attachments#edit_all', :as => :object_attachments_edit
    patch 'attachments/:object_type/:object_id', :to => 'attachments#update_all', :as => :object_attachments
    get 'attachments/:object_type/:object_id/download', :to => 'attachments#download_all', :as => :object_attachments_download
  end

  resources :groups do
    resources :memberships, :controller => 'principal_memberships'
    member do
      get 'autocomplete_for_user'
    end
  end

  get 'groups/:id/users/new', :to => 'groups#new_users', :id => /\d+/, :as => 'new_group_users'
  post 'groups/:id/users', :to => 'groups#add_users', :id => /\d+/, :as => 'group_users'
  delete 'groups/:id/users/:user_id', :to => 'groups#remove_user', :id => /\d+/, :as => 'group_user'

  resources :trackers, :except => :show do
    collection do
      match 'fields', :via => [:get, :post]
    end
  end
  resources :issue_statuses, :except => :show do
    collection do
      post 'update_issue_done_ratio'
    end
  end
  resources :custom_fields, :except => :show do
    resources :enumerations, :controller => 'custom_field_enumerations', :except => [:show, :new, :edit]
    put 'enumerations', :to => 'custom_field_enumerations#update_each'
  end
  resources :roles do
    collection do
      get 'permissions'
      post 'permissions', :to => 'roles#update_permissions'
    end
  end
  resources :enumerations, :except => :show
  match 'enumerations/:type', :to => 'enumerations#index', :via => :get

  get '(projects/:id)/search', :controller => 'search', :action => 'index', :as => 'search'


  get  'mail_handler', :to => 'mail_handler#new'
  post 'mail_handler', :to => 'mail_handler#index'

  get 'admin', :to => 'admin#index'
  get 'admin/projects', :to => 'admin#projects'
  get 'admin/plugins', :to => 'admin#plugins'
  get 'admin/info', :to => 'admin#info'
  post 'admin/test_email', :to => 'admin#test_email', :as => 'test_email'
  post 'admin/default_configuration', :to => 'admin#default_configuration'

  match '/admin/projects_context_menu', :to => 'context_menus#projects', :as => 'projects_context_menu', :via => [:get, :post]

  resources :auth_sources do
    member do
      get 'test_connection', :as => 'try_connection'
    end
    collection do
      get 'autocomplete_for_new_user'
    end
  end

  resources :workflows, only: [:index] do
    collection do
      get 'edit'
      patch 'update'
      get 'permissions'
      patch 'update_permissions'
      get 'copy'
      post 'duplicate'
    end
  end

  match 'settings', :controller => 'settings', :action => 'index', :via => :get
  match 'settings/edit', :controller => 'settings', :action => 'edit', :via => [:get, :post]
  match 'settings/plugin/:id', :controller => 'settings', :action => 'plugin', :via => [:get, :post], :as => 'plugin_settings'

  match 'sys/projects', :to => 'sys#projects', :via => :get
  match 'sys/projects/:id/repository', :to => 'sys#create_project_repository', :via => :post
  match 'sys/fetch_changesets', :to => 'sys#fetch_changesets', :via => [:get, :post]

  match 'uploads', :to => 'attachments#upload', :via => :post

  get 'robots.:format', :to => 'welcome#robots', :constraints => {:format => 'txt'}

  get 'help/wiki_syntax/(:type)', :controller => 'help', :action => 'show_wiki_syntax', :constraints => { :type => /detailed/ }, :as => 'help_wiki_syntax'
  get 'help/code_highlighting', :controller => 'help', :action => 'show_code_highlighting',  :as => 'help_code_highlighting'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  Redmine::Plugin.directory.glob("*/config/routes.rb").sort.each do |plugin_routes_path|
    instance_eval(plugin_routes_path.read, plugin_routes_path.to_s)
  rescue SyntaxError, StandardError => e
    plugin_name = plugin_routes_path.parent.parent.basename.to_s
    puts "An error occurred while loading the routes definition of #{plugin_name} plugin (#{plugin_routes_path}): #{e.message}."

redmine-6.0.4/app/helpers/workflows_helper.rb
# frozen_string_literal: true

# Redmine - project management software
# Copyright (C) 2006-  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module WorkflowsHelper
  def options_for_workflow_select(name, objects, selected, options={})
    option_tags = ''.html_safe
    multiple = false
    if selected
      if selected.size == objects.size
        selected = 'all'
      else
        selected = selected.map(&:id)
        if selected.size > 1
          multiple = true
        end
      end
    else
      selected = objects.first.try(:id)
    end
    all_tag_options = {:value => 'all', :selected => (selected == 'all')}
    if multiple
      all_tag_options[:style] = "display:none;"
    end
    option_tags << content_tag('option', l(:label_all), all_tag_options)
    option_tags << options_from_collection_for_select(objects, "id", "name", selected)
    select_tag name, option_tags, {:multiple => multiple}.merge(options)
  end

  def field_required?(field)
    field.is_a?(CustomField) ? field.is_required? : %w(project_id tracker_id subject priority_id is_private).include?(field)
  end

  def field_permission_tag(permissions, status, field, roles)
    name = field.is_a?(CustomField) ? field.id.to_s : field
    options = [["", ""], [l(:label_readonly), "readonly"]]
    options << [l(:label_required), "required"] unless field_required?(field)
    html_options = {}

    if perm = permissions[status.id][name]
      if perm.uniq.size > 1 || perm.size < @roles.size * @trackers.size
        options << [l(:label_no_change_option), "no_change"]
        selected = 'no_change'
      else
        selected = perm.first
      end
    end

    hidden = field.is_a?(CustomField) &&
      !field.visible? &&
      !roles.detect {|role| role.custom_fields.to_a.include?(field)}

    if hidden
      options[0][0] = l(:label_hidden)
      selected = ''
      html_options[:disabled] = true
    end

    select_tag("permissions[#{status.id}][#{name}]", options_for_select(options, selected), html_options)
  end

  def transition_tag(transition_count, old_status, new_status, name)
    w = transition_count
    tag_name = "transitions[#{ old_status.try(:id) || 0 }][#{new_status.id}][#{name}]"
    if old_status == new_status
      check_box_tag(tag_name, "1", true,
                    {:disabled => true, :class => "old-status-#{old_status.try(:id) || 0} new-status-#{new_status.id}"})
    elsif w == 0 || w == @roles.size * @trackers.size
      hidden_field_tag(tag_name, "0", :id => nil) +
      check_box_tag(tag_name, "1", w != 0,
                    :class => "old-status-#{old_status.try(:id) || 0} new-status-#{new_status.id}")
    else
      select_tag(
        tag_name,
        options_for_select(
          [
            [l(:general_text_Yes), "1"],
            [l(:general_text_No), "0"],
            [l(:label_no_change_option), "no_change"]
          ],
          "no_change")
      )
    end
  end
end

redmine-6.0.4/app/views/workflows/_action_menu.html.erb
<div class="contextual">
<%= link_to sprite_icon('copy', l(:button_copy)), { :action => 'copy'}, :class => 'icon icon-copy' %>
<%= link_to sprite_icon('summary', l(:field_summary)), { :action => 'index'}, :class => 'icon icon-summary' %>
</div>

redmine-6.0.4/app/views/workflows/_form.html.erb
<table class="list workflows transitions transitions-<%= name %>">
<thead>
  <tr>
    <th>
      <%= toggle_checkboxes_link("table.transitions-#{name} input[type=checkbox]:not(:disabled)", { class: 'no-tooltip' }) %>
      <%=l(:label_current_status)%>
    </th>
    <th colspan="<%= @statuses.length %>"><%=l(:label_new_statuses_allowed)%></th>
  </tr>
  <tr>
    <td></td>
    <% for new_status in @statuses %>
    <td style="width:<%= 75 / @statuses.size %>%;">
      <%= toggle_checkboxes_link("table.transitions-#{name} input[type=checkbox]:not(:disabled).new-status-#{new_status.id}", { class: 'no-tooltip' }) %>
      <%= new_status.name %>
    </td>
    <% end %>
  </tr>
</thead>
<% transition_counts = workflows.each_with_object(Hash.new(0)) {|w,memo| memo[[w.old_status, w.new_status]] += 1} %>
<tbody>
  <% for old_status in [nil] + @statuses %>
  <% next if old_status.nil? && name != 'always' %>
  <tr>
    <td class="name">
      <%= toggle_checkboxes_link("table.transitions-#{name} input[type=checkbox]:not(:disabled).old-status-#{old_status.try(:id) || 0}", { class: 'no-tooltip' }) %>
      <% if old_status %>
        <% old_status_name = old_status.name %>
        <%= old_status_name %>
      <% else %>
        <% old_status_name = l(:label_issue_new) %>
        <%= content_tag('em', old_status_name) %>
      <% end %>
    </td>
    <% for new_status in @statuses -%>
    <% checked = (old_status == new_status) || (transition_counts[[old_status, new_status]] > 0) %>
    <td class="no-tooltip <%= checked ? 'enabled' : '' %>" title="<%= old_status_name %> &#187; <%= new_status.name %>">
      <%= transition_tag transition_counts[[old_status, new_status]], old_status, new_status, name %>
    </td>
    <% end -%>
  </tr>
  <% end %>
</tbody>
</table>

redmine-6.0.4/app/views/workflows/copy.html.erb
<%= title [l(:label_workflow), edit_workflows_path], l(:button_copy) %>

<%= form_tag duplicate_workflows_path, method: :post, id: 'workflow_copy_form' do %>
<fieldset class="tabular box">
<legend><%= l(:label_copy_source) %></legend>
<p>
  <label><%= l(:label_tracker) %></label>
  <%= select_tag('source_tracker_id',
                  content_tag('option', "--- #{l(:actionview_instancetag_blank_option)} ---", :value => '') +
                  content_tag('option', "--- #{ l(:label_copy_same_as_target) } ---", :value => 'any') +
                  options_from_collection_for_select(@trackers, 'id', 'name', @source_tracker && @source_tracker.id)) %>
</p>
<p>
  <label><%= l(:label_role) %></label>
  <%= select_tag('source_role_id',
                  content_tag('option', "--- #{l(:actionview_instancetag_blank_option)} ---", :value => '') +
                  content_tag('option', "--- #{ l(:label_copy_same_as_target) } ---", :value => 'any') +
                  options_from_collection_for_select(@roles, 'id', 'name', @source_role && @source_role.id)) %>
</p>
</fieldset>

<fieldset class="tabular box">
<legend><%= l(:label_copy_target) %></legend>
<p>
  <label><%= l(:label_tracker) %></label>
  <%= select_tag 'target_tracker_ids',
                  content_tag('option', "--- #{l(:actionview_instancetag_blank_option)} ---", :value => '', :disabled => true) +
                  options_from_collection_for_select(@trackers, 'id', 'name', @target_trackers && @target_trackers.map(&:id)), :multiple => true %>
</p>
<p>
  <label><%= l(:label_role) %></label>
  <%= select_tag 'target_role_ids',
                  content_tag('option', "--- #{l(:actionview_instancetag_blank_option)} ---", :value => '', :disabled => true) +
                  options_from_collection_for_select(@roles, 'id', 'name', @target_roles && @target_roles.map(&:id)), :multiple => true %>
</p>
</fieldset>
<%= submit_tag l(:button_copy) %>
<% end %>

redmine-6.0.4/app/views/workflows/edit.html.erb
<%= render :partial => 'action_menu' %>

<%= title l(:label_workflow) %>

<div class="tabs">
  <ul>
    <li><%= link_to l(:label_status_transitions), edit_workflows_path(:role_id => @roles, :tracker_id => @trackers), :class => 'selected' %></li>
    <li><%= link_to l(:label_fields_permissions), permissions_workflows_path(:role_id => @roles, :tracker_id => @trackers) %></li>
  </ul>
</div>

<p><%=l(:text_workflow_edit)%>:</p>

<%= form_tag({}, :method => 'get') do %>
<p>
  <label><%=l(:label_role)%>:
  <%= options_for_workflow_select 'role_id[]', Role.sorted.select(&:consider_workflow?), @roles, :id => 'role_id', :class => 'expandable' %>
  <span class="toggle-multiselect icon-only"><%= sprite_icon('') %></span>
  </label>

  <label><%=l(:label_tracker)%>:
  <%= options_for_workflow_select 'tracker_id[]', Tracker.sorted, @trackers, :id => 'tracker_id', :class => 'expandable' %>
  <span class="toggle-multiselect icon-only"><%= sprite_icon('') %></span>
  </label>

  <%= submit_tag l(:button_edit), :name => nil %>

  <%= hidden_field_tag 'used_statuses_only', '0', :id => nil %>
  <label><%= check_box_tag 'used_statuses_only', '1', @used_statuses_only %> <%= l(:label_display_used_statuses_only) %></label>

</p>
<% end %>

<% if @trackers && @roles && @statuses.any? %>
  <%= form_tag workflows_path, method: :patch, id: 'workflow_form' do %>
    <%= @trackers.map {|tracker| hidden_field_tag 'tracker_id[]', tracker.id, :id => nil}.join.html_safe %>
    <%= @roles.map {|role| hidden_field_tag 'role_id[]', role.id, :id => nil}.join.html_safe %>
    <%= hidden_field_tag 'used_statuses_only', params[:used_statuses_only], :id => nil %>
    <div class="autoscroll">
      <%= render :partial => 'form', :locals => {:name => 'always', :workflows => @workflows['always']} %>

      <fieldset class="collapsible" style="padding: 0; margin-top: 0.5em;">
        <legend onclick="toggleFieldset(this);" class="icon icon-collapsed">
          <%= sprite_icon("angle-right") %>
          <%= l(:label_additional_workflow_transitions_for_author) %>
        </legend>
        <div id="author_workflows" style="margin: 0.5em 0 0.5em 0;">
          <%= render :partial => 'form', :locals => {:name => 'author', :workflows => @workflows['author']} %>
        </div>
      </fieldset>
      <%= javascript_tag "hideFieldset($('#author_workflows'))" unless @workflows['author'].present? %>

      <fieldset class="collapsible" style="padding: 0;">
        <legend onclick="toggleFieldset(this);" class="icon icon-collapsed">
          <%= sprite_icon("angle-right") %>
          <%= l(:label_additional_workflow_transitions_for_assignee) %>
        </legend>
        <div id="assignee_workflows" style="margin: 0.5em 0 0.5em 0;">
      <%= render :partial => 'form', :locals => {:name => 'assignee', :workflows => @workflows['assignee']} %>
        </div>
      </fieldset>
      <%= javascript_tag "hideFieldset($('#assignee_workflows'))" unless @workflows['assignee'].present? %>
    </div>
    <%= submit_tag l(:button_save) %>
  <% end %>
<% end %>

redmine-6.0.4/app/views/workflows/index.html.erb
<%= title [l(:label_workflow), edit_workflows_path], l(:field_summary) %>

<% if @roles.empty? || @trackers.empty? %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
<div class="autoscroll">
<table class="list">
<thead>
    <tr>
    <th></th>
    <% @roles.each do |role| %>
    <th>
        <%= content_tag(role.builtin? ? 'em' : 'span', role.name) %>
    </th>
    <% end %>
    </tr>
</thead>
<tbody>
<% @trackers.each do |tracker| -%>
<tr>
  <td class="name"><%= tracker.name %></td>
  <% @roles.each do |role| -%>
  <% count = @workflow_counts[[tracker.id, role.id]] || 0 %>
    <td>
      <%= link_to(count,
                  {:action => 'edit', :role_id => role, :tracker_id => tracker},
                  :title => l(:button_edit), :class => ('decoration-red' if count == 0)) %>
    </td>
  <% end -%>
</tr>
<% end -%>
</tbody>
</table>
</div>
<% end %>

redmine-6.0.4/app/views/workflows/permissions.html.erb
<%= render :partial => 'action_menu' %>

<%= title l(:label_workflow) %>

<div class="tabs">
  <ul>
    <li><%= link_to l(:label_status_transitions), edit_workflows_path(:role_id => @roles, :tracker_id => @trackers) %></li>
    <li><%= link_to l(:label_fields_permissions), permissions_workflows_path(:role_id => @roles, :tracker_id => @trackers), :class => 'selected' %></li>
  </ul>
</div>

<p><%=l(:text_workflow_edit)%>:</p>

<%= form_tag({}, :method => 'get') do %>
<p>
  <label><%=l(:label_role)%>:
  <%= options_for_workflow_select 'role_id[]', Role.sorted.select(&:consider_workflow?), @roles, :id => 'role_id', :class => 'expandable' %>
  <span class="toggle-multiselect icon-only"><%= sprite_icon('') %></span>
  </label>

  <label><%=l(:label_tracker)%>:
  <%= options_for_workflow_select 'tracker_id[]', Tracker.sorted, @trackers, :id => 'tracker_id', :class => 'expandable' %>
  <span class="toggle-multiselect icon-only"><%= sprite_icon('') %></span>
  </label>
  <%= submit_tag l(:button_edit), :name => nil %>

  <%= hidden_field_tag 'used_statuses_only', '0', :id => nil %>
  <label><%= check_box_tag 'used_statuses_only', '1', @used_statuses_only %> <%= l(:label_display_used_statuses_only) %></label>
</p>
<% end %>

<% if @trackers && @roles && @statuses.any? %>
  <%= form_tag update_permissions_workflows_path, method: :patch, id: 'workflow_form' do %>
    <%= @trackers.map {|tracker| hidden_field_tag 'tracker_id[]', tracker.id, :id => nil}.join.html_safe %>
    <%= @roles.map {|role| hidden_field_tag 'role_id[]', role.id, :id => nil}.join.html_safe %>
    <%= hidden_field_tag 'used_statuses_only', params[:used_statuses_only], :id => nil %>
    <div class="autoscroll">
    <table class="list workflows fields_permissions">
    <thead>
      <tr>
        <th>
        </th>
        <th colspan="<%= @statuses.length %>"><%=l(:label_issue_status)%></th>
      </tr>
      <tr>
        <td></td>
        <% for status in @statuses %>
        <td style="width:<%= 75 / @statuses.size %>%;">
          <%= status.name %>
        </td>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <tr class="group open">
        <td colspan="<%= @statuses.size + 1 %>">
          <span class="expander icon icon-expanded" onclick="toggleRowGroup(this);"><%= sprite_icon("angle-down") %></span>
          <%= l(:field_core_fields) %>
        </td>
      </tr>
      <% @fields.each do |field, name| %>
      <tr>
        <td class="name">
          <%= name %> <%= content_tag('span', '*', :class => 'required') if field_required?(field) %>
        </td>
        <% for status in @statuses -%>
        <td class="<%= @permissions[status.id][field].try(:join, ' ') %>" title="<%= name %> (<%= status.name %>)">
          <%= field_permission_tag(@permissions, status, field, @roles) %>
          <% unless status == @statuses.last %><a href="#" class="repeat-value" title="<%= l(:button_copy) %>">&#187;</a><% end %>
        </td>
        <% end -%>
      </tr>
      <% end %>
      <% if @custom_fields.any? %>
        <tr class="group open">
          <td colspan="<%= @statuses.size + 1 %>">
            <span class="expander icon icon-expanded" onclick="toggleRowGroup(this);"><%= sprite_icon("angle-down") %></span>
            <%= l(:label_custom_field_plural) %>
          </td>
        </tr>
        <% @custom_fields.each do |field| %>
        <tr>
          <td class="name">
            <%= field.name %> <%= content_tag('span', '*', :class => 'required') if field_required?(field) %>
          </td>
          <% for status in @statuses -%>
          <td class="<%= @permissions[status.id][field.id.to_s].try(:join, ' ') %>" title="<%= field.name %> (<%= status.name %>)">
            <%= field_permission_tag(@permissions, status, field, @roles) %>
            <% unless status == @statuses.last %><a href="#" class="repeat-value">&#187;</a><% end %>
          </td>
          <% end -%>
        </tr>
        <% end %>
      <% end %>
    </tbody>
    </table>
    </div>
    <%= submit_tag l(:button_save) %>
  <% end %>
<% end %>

<%= javascript_tag do %>
$("a.repeat-value").click(function(e){
  e.preventDefault();
  var td = $(this).closest('td');
  var selected = td.find("select").find(":selected").val();
  td.nextAll('td').find("select").val(selected);
});
<% end %>